### ISSUE TITLE
[features] Seatの着席リクエストの作成

### ISSUE THREAD

**Issue by 9-sho-5** [OverAgers/iruyan#44]
# 概要
Seatの着席リクエストの作成

# 目的
Seatに着席するためのリクエスト

httpメソッド | パス
-- | --
/room/:room_id/seats/:seat_id/take | room_id <br> seat_id

# 依存タスク
- [x] #57

**Comment by oyui7272** [comment]
下記の設計であっているでしょうか？
- httpメソッド：PATCH
- パス：/rooms/:room_id/seats/:seat_id/take
- リクエストボディ：user_id

パス変数にseat_idを使うか、seat_numbetを使うか、念の為確認お願いします...！
WorkTimeモデルのカラム名はSeatNumberになっていました。

**Comment by oyui7272** [comment]
パス名はseat_idですが、実際にはseat_idの部分にseat_numberを書いて呼び出している、一部矛盾したコードのままプッシュしてしまいました...。🙇‍♀️
今のところ、内部の処理はseat_numberで行っています。

どちらを使うか確認とれ次第、修正して再度プッシュします！
