### ISSUE TITLE
[features] Seatの離席リクエストの作成

### ISSUE THREAD

**Issue by 9-sho-5** [OverAgers/iruyan#45]
# 概要
Seatの離席リクエストの作成

# 目的
Seatに離席するためのリクエスト

httpメソッド | パス
-- | --
/room/:room_id/seats/:seat_id/leave | room_id <br> seat_id

**Comment by oyui7272** [comment]
リクエストにある `seat_id` は、ユーザーがその座席に座っていることを確認した上で離席させる（`seat_number` に0を割り当てる）ために使用するという認識で合っていますでしょうか？

それとも、`seat_id` は不要で、リクエストボディとして受け取る `user_id` とパス変数`room_id`を用いてDBから該当する行を見つけ、自動的にseat_number 0を割り当てるような実装になるのでしょうか？

色んなissueで質問送っていて、お手数おかけして申し訳ないです🙇‍♀️
