### ISSUE TITLE
[features] ユーザー画面の取得リクエスト

### ISSUE THREAD

**Issue by 9-sho-5** [OverAgers/iruyan#56]
# 概要
ユーザー画面の取得リクエストの作成

# 目的
ユーザー画面を取得するためのリクエスト

httpメソッド | パス | データ
-- | -- | --
GET | /user/:user_id | room_id

# 要件
ユーザーが見つかったら、200を返す
見つからなかったら、User Not Found(400)を返す

**Comment by oyui7272** [comment]
httpメソッド：GET, パス：/user/:user_idでしょうか？

**Comment by 9-sho-5** [comment]
@oyui7272 
修正しておいた！
